create table if not exists public.job_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null,
  source_id text not null,
  title text,
  company text,
  location text,
  url text,
  score integer,
  status text not null default 'review',
  recipient text,
  notes text,
  unique (source, source_id)
);

create index if not exists job_applications_created_at_idx on public.job_applications (created_at desc);
create index if not exists job_applications_status_idx on public.job_applications (status);
